### ISSUE TITLE
Any interest in adding the tests to xdis? 

### ISSUE THREAD

**Issue by rocky** [moagstar/backports.dis#1]
Hi - I just noticed this and noticed you've revised the tests for 2.7. Any interest in getting those tests into xdis. It sure could use the 3x ish tests. Thanks.

**Comment by moagstar** [comment]
Yes I think it's definitely worth adding the standard tests to xdis, however I've kind of abandoned this project for now, especially since I saw you are already working on a much more useful module! So I think it's perhaps best just to try and integrate the standard tests from python 3, and maybe see if there are some interesting code objects here which can also be added.

**Comment by moagstar** [comment]
I closed this issue and created a new issue in xdis:
https://github.com/rocky/python-xdis/issues/1
